language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.7,<1.8"


install:
  - pip install -U mock coverage coveralls django-etc $DJANGO

script: coverage run -a --source=sitemessage sitemessage/runtests.py

matrix:

  exclude:
   - python: 3.6
     env: DJANGO="Django>=1.7,<1.8"

   - python: 3.5
     env: DJANGO="Django>=1.7,<1.8"


after_success:
  coveralls
